### PR TITLE
Add yourself to CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by tbekolay**
We have a bunch of new contributors that haven't signed the CONTRIBUTORS.md file. We need to do this before releasing. Below are the people that I think have to be added; if you're on this list please make a commit adding yourself to CONTRIBUTORS.md on this branch.

ping @jgosmann @xchoo

### CODE REVIEW

**Comment by hunse** [comment]
Oh, sorry, I just went for it!

**Comment by tbekolay** [comment]
:-o that's probs okay

**Comment by tbekolay** [comment]
3 down, 4 to go ;)

**Comment by tbekolay** [comment]
Another ping for @jgosmann @xchoo. I know you guys are getting this email!

**Comment by tbekolay** [comment]
Whoops, my bad @jgosmann's already on here, I just missed the commit due to the white background in your icon ;) @xchoo is holding up the parade!

**Pull request merged**
