### PR TITLE
Use signal handlers for shutdown confirmation.

### LINKED ISSUE #234: Shutdown with double Ctrl+C
An IPython notebook server can be shut down by pressing Ctrl+C twice (in addition to Ctrl+C, y, enter). Doing this with nengo_viz just kills the server without shutting it down properly.

### PR DESCRIPTION
**Pull request by jgosmann**
Closes #234.

### CODE REVIEW

**Comment by tbekolay** [comment]
Just tried this; works great on Mac OS X! Obviously the real test is Windows though, which I don't have access to. Any Windows users able to test this branch?

**Comment by jgosmann** [comment]
I tested it in my VM and worked. (Doesn't ask for confirmation on Windows because it does not support select on anything that is not a socket. This is in line with what ipython notebook does.)

**Comment by tcstewar** [comment]
I'm happy with it not asking for confirmation on windows.

**Comment by tbekolay** [comment]
Kay, ready to merge then?

**Pull request merged**
