### PR TITLE
Do not propagate space keydown from button.

### LINKED ISSUE #302: Spacebar does not properly start/stop the simulation if focus is on the play button in Firefox
Firefox strikes again! If you click play with your mouse to start the simulation, the spacebar hotkey will not work properly. It will stop the simulation when you press it, but then start it again immediately when you release it. I think this is because when you have focus on the button, enter and spacebar will act like you clicked on it, essentially sending play/pause commands in pairs of two. This issue doesn't happen on Chrome of course.

### PR DESCRIPTION
**Pull request by jgosmann**
Fixes #302.

### CODE REVIEW

**Comment by cchan987** [comment]
Looks good to me

**Comment by tbekolay** [comment]
Cool, merging!

**Comment by tbekolay** [comment]
Actually @bjkomer can you test this branch quickly? I'll merge on your okay.

**Comment by tbekolay** [comment]
n/m, I managed to reproduce the issue and this fixed it for me.

**Pull request merged**
