### PR TITLE
Fixed dropped websocket messages

### PR DESCRIPTION
**Pull request by tcstewar**
Stops the websocket system from ignoring messages to the server

### CODE REVIEW

**Comment by hunse** [comment]
I've been testing the first commit in one of my branches, and it works like a charm, or at least the dropped messages I was encountering before aren't getting dropped anymore.

**Comment by tcstewar** [comment]
> I've been testing the first commit in one of my branches, and it works like a charm, or at least the dropped messages I was encountering before aren't getting dropped anymore.

Yay!  I'm very happy to have this fix...  This was causing annoyances in many places in the code....  I still feel pretty embarrassed for having made this mistake in the first place.

**Comment by tcstewar** [comment]
Are we happy with the review on this PR?  I'd like to merge it...  :)

**Comment by tbekolay** [comment]
LGTM!

**Pull request merged**
