### PR TITLE
look for -webkit-transform if transform undefine

### PR DESCRIPTION
**Pull request by studywolf**
quick fix for #190

### CODE REVIEW

**Comment by tcstewar** [comment]
It looks like on some older versions of Chrome, the ```transform``` attribute gets ignored and it uses ```-webkit-transform``` instead.  We're handling that in ```VIZ.set_transform``` and this PR makes it so we handle it in ```VIZ.get_transform``` as well.

**Comment by tcstewar** [comment]
(and it looks good to me, but I wouldn't mind another set of eyes on it before I merge it)

**Comment by tcstewar** [comment]
I took @hunse 's suggestion and also reformatted a bit to respect line lengths....  

@studywolf does this still fix the problem for you?  If you could quickly confirm that I'll merge it in.

**Comment by hunse** [comment]
Also fix up the commit message a bit before merge. "undefined" is missing its second 'd', and it would be nice to have a bit of a body to say that this was a problem that happened on Chrome, etc.

**Comment by studywolf** [comment]
yup can drag things!

**Pull request merged**
