### PR TITLE
Shutdown server when last webpage closes

### PR DESCRIPTION
**Pull request by tcstewar**
Addresses #205 

The Viz object now keeps track of a list of VizSim objects.  VizSims remove themselves from that list when they are done.

When a websocket closes, it checks that list to see if it's empty.  If it is, then it shuts down the server.

For this to work, the SimControl on the server side has been modified to send out WebSocket ping events every 2 seconds (otherwise there's no way to realize the webpage has closed).

There's no configuration option yet, but I'll add that when #208 is merged.

### CODE REVIEW

**Comment by tcstewar** [comment]
Rebased this to master so it can be reviewed...

**Comment by tbekolay** [comment]
I can't speak too much to the code (looks good to me?) but the user experience of this is excellent! It feels much cleaner for the server to shut down once the tabs are closed. The only thing that I would like is for an explanatory message to be printed to the console. Right now, once you close all the tabs it just prints `Shutting down server...` like before. It'd be good for it to explain why it's shutting down the server; something like `No more connections to the nengo_viz server. Shutting down server...`. As a user, I'd be impressed to see that message ;)

**Comment by tcstewar** [comment]
> It'd be good for it to explain why it's shutting down the server;

I've added that message now.  I also had to change the logic slightly so that it wasn't trying to shut the server down multiple times (and thus printing multiple messages).  Now only the SimControl websocket checks for shutdowns

**Comment by tbekolay** [comment]
Awesome, LGTM! I'd be keen to merge this in quickly, it's quite an improvement for user experience.

**Comment by tcstewar** [comment]
> Awesome, LGTM! I'd be keen to merge this in quickly, it's quite an improvement for user experience.

Your wish is my command!  :)

**Comment by studywolf** [comment]
goodness this makes things better!

**Pull request merged**
