### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by jgosmann**
See commit messages.

Summary:
* Fix speed and time display in sim control.
* Style the top toolbar to match sim control.

### CODE REVIEW

**Comment by tcstewar** [comment]
Nice.   :)

I do find the blue highlighting on hover a little too subtle....   perhaps a border around the button on hover?

```
#top_toolbar .glyphicon {
    color: #333;
    cursor: default;
    top: 0;
    border: solid 1px #eee;
}

#top_toolbar .glyphicon:hover {
    background: #d9edf7;
    border: solid 1px #ccc;
}
```

**Comment by jgosmann** [comment]
Oh yeah, I forgot to mention that we might want to make the highlighting a bit less subtle.
I chose the color because it matches the color in the time bar ...

**Comment by jgosmann** [comment]
Not sure how much I like the border. I changed it to invert fore- and background color on hover. What do you think about that?

**Comment by tcstewar** [comment]
> Not sure how much I like the border. I changed it to invert fore- and background color on hover. What do you think about that?

Interesting..  it's a bit harsh of a contrast, but I like the general idea.  Maybe less dark a background on hover?

Also, I think the play/pause/build button in the bottom-right should by styled similarly to the top toolbar buttons.

**Comment by jgosmann** [comment]
Reduced the contrast and applied the same hover style to the play/pause button. (I don't think the normal style should be changed, because the brighter background makes it more easy to identify as a clickable button. Otherwise it would have the same color as the background.)

**Comment by celiasmith** [comment]
+1 to both of terry's comments

**Comment by celiasmith** [comment]
now it doesn't look the same as the other buttons.... i think the point was to make it look like those other ones (no background)

**Comment by celiasmith** [comment]
not sure if this is styling as well, but the filename cursor changes (to a text selector, which you can't do)... either you should be able to select the text or the cursor shouldn't change.

**Comment by jgosmann** [comment]
Filename cursor should be fixed with the last commit.
As I said, I don't agree that the play/pause button should have no background.

**Comment by celiasmith** [comment]
Do you want to make them all have a background then?  Or do you think they're good just being different?

**Comment by celiasmith** [comment]
The cursor is still not fixed for me.

**Comment by celiasmith** [comment]
I just did a commit to see what it looks like to make all the buttons the same.  Thoughts of this vs having the bottom one different?

**Comment by tbekolay** [comment]
One style thing about the top toolbar that I really dislike is the rounding on the toolbar buttons. It makes it seem like they're not actually supposed to be lined up beside each other, because there's a weird bit of negative space were they all to be hovered on at the same time.

Setting border-radius to 0px, or none, should fix it.

**Comment by studywolf** [comment]
i liked the blue,... it looks so boring as light grey...

**Comment by celiasmith** [comment]
I thought that, but all the colours come from data!  so then i felt better...

**Comment by studywolf** [comment]
data?

**Comment by celiasmith** [comment]
run the model and the graphs are all coloured :)

**Comment by jgosmann** [comment]
> The cursor is still not fixed for me. I think it should be 'default' instead of 'pointer'

Depends on what the cursor should be. I think, when I tested it first it was 'pointer' and I like it that way. But if people prefer 'default', that's good too.

> I just did a commit to see what it looks like to make all the buttons the same. Thoughts of this vs having the bottom one different?

I don't like it. It's common to have toolbars without visible button borders, so it's obvious enough that icons in a row at the top of a window are clickable. But this is not as obvious for the sim control. It could just be a text marker direction of time. And I can't think of any software where non-toolbar buttons don't have any border.

> i liked the blue,... it looks so boring as light grey...

I don't think control elements like the toolbar should be too brightly colored because that's not what the focus of attention should be. Having some more color in there could be nice, but we should be careful where we add it. One thing I could imagine is to use a different hover background color.

**Comment by jgosmann** [comment]
and I removed the rounded corners from the toolbar buttons

**Comment by studywolf** [comment]
Color can be a settings thing!

**Comment by jgosmann** [comment]
We could make everything styleable with user CSS. :P

As a general note: I don't think, we should make every conceivable thing a user option.

**Comment by tcstewar** [comment]
> As a general note: I don't think, we should make every conceivable thing a user option.

I'd second that note...  it's the same sort of principle as Python's "There should be one-- and preferably only one --obvious way to do it."  :)

**Comment by studywolf** [comment]
I don't think anyone is advocating for every conceivable option, friends.
Color is clearly a preference and rather than argue about it i thought we
could have an easy fix where users can set it however they want.

As a general note: I don't think, we should make every conceivable thing a
user option.

I'd second that note... it's the same sort of principle as Python's "There
should be one-- and preferably only one --obvious way to do it." :)

—
Reply to this email directly or view it on GitHub
<https://github.com/nengo/nengo_viz/pull/219#issuecomment-106621893>.

**Comment by tcstewar** [comment]
> Color is clearly a preference and rather than argue about it i thought we
> could have an easy fix where users can set it however they want.

True, but even if we did have such an option, we'd still have to have exactly this argument over what the default should be.  And once we've decided on a default, I'm not sure we gain much by having it be configurable.  Mostly I'm trying to avoid the "giant page of configuration options" problem that's prevalent in other software, so I don't think we should get in the habit of creating new configuration options.  I'd much prefer to decide on a look and feel and stick with that.

That said, I really shouldn't be allowed a vote on any colour-based look and feel options.  :)

**Comment by celiasmith** [comment]
(Hopefully not a duplicate comment, as I emailed it, but it's not showing up here)

On button borders: The email reader I'm using now has no borders on both top and bottom bar buttons.  This is very common in mobile. If you google flat ui design you'll see many examples.

Adding: On the cursor, the original change to 'pointer' didn't do anything (which is why I suggested default), the commit I added fixed that problem (it was different css that had to change).  As for pointer vs default, I suspect we need to compare these across OSs, 'pointer' on a mac is a finger...

On colours, we should talk in person.  My impression is that Linux apps tend to have a .settings file where you can change everything about the app (often not in a menu); not so for windows and mac, where look and feel is more constrained.  User css would kind of do the linux thing, for better or worse.

**Comment by jgosmann** [comment]
The examples I find on Google seem to support my view. But I think, I explained my view and if the majority prefers no border, I'm fine with that.

Introducing settings for colors could lead to a vast amount of options and might be wasted developer time. How many users will actually care enough to change those options? Allowing user CSS seems to be the best option to me, because it should be fairly easy to implement and gives all the flexibility. But before that we might want to clean up the HTML structure, IDs, and class names a bit to have a clear structure for styling.

That being said, I think there is one case where configurable colors of some sort are quite important: The syntax highlighting in the editor. And while I'm talking about it: I propose [Solarized](http://ethanschoonover.com/solarized) (which comes in a dark and a light version) as default.

**Comment by studywolf** [comment]
Sure, in which case I vote for a darker gray or ideally a color for the top
bar. It kind of blends into the white background at the moment and that is
a bit headache-y.

I would actually think that the syntax highlighting would be a case where
the configuration wouldn't matter really, since it's also designed for
people to use their own editor instead...

**Comment by jgosmann** [comment]
> since it's also designed for people to use their own editor instead...

I guess, that's true

**Comment by tcstewar** [comment]
Cool, this is definitely an improvement now, so I'm going to merge it.  I'm quite sure there will be more styling issues for future PRs....  :)

**Pull request merged**
